### ISSUE TITLE
header 加上  <meta name=”viewport”>

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/demo-pttbbs#124]
https://medium.com/frochu/html-meta-viewport-setting-69fbb06ed3d8

某大大希望可以先如此在 mobile 上 work-around～

使用 < meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" >

**Comment by IepIweidieng** [comment]
現在已經是如此設定的了，那我們可以關閉了？

**Comment by chhsiao1981** [comment]
以下圖是我使用 chrome + iOS X 的結果.
viewport 似乎是有達到預期效果.

但是在 title 的字數多的時候有破版的問題.
並且似乎沒有辦法往上移動.

先關閉這個 issue.
然後開其他 issues 來追蹤相關問題.

![IMG_1603](https://user-images.githubusercontent.com/2970164/211553175-ad3b97d5-5b80-424a-a43f-169b5be89e14.PNG)

![IMG_1604](https://user-images.githubusercontent.com/2970164/211553281-fa961052-3220-4e9c-b656-cf698b90af98.PNG)

![IMG_1605](https://user-images.githubusercontent.com/2970164/211553291-623edb74-afe1-42c3-90ee-7aec2c3e3dfd.PNG)

![IMG_1606](https://user-images.githubusercontent.com/2970164/211553316-b0874827-3643-45e8-aae6-7a226747a540.PNG)

![IMG_1607](https://user-images.githubusercontent.com/2970164/211553334-19b0d1fb-3546-430e-9b7f-a8fe854e073c.PNG)

![IMG_1608](https://user-images.githubusercontent.com/2970164/211553353-60ce2e6a-839e-4cd5-b9bf-b01df334347c.PNG)

**Comment by chhsiao1981** [comment]
另外是這個 repo 目前可以先 focus 在 desktop 的 16:9 / 16:10 上.

mobile 相關的 priority 先放低.

**Comment by IepIweidieng** [comment]
這個有個盲點，就是桌面裝置使用者可能同時開啟多個視窗操作（比如文書編輯或資訊比較），或是擁有非平凡長寬比的顯示裝置，而造成畫面不接近 16:9–10（不可能眞的等於 16:9∨10，除非進入全螢幕模式）。不過這確實可以在未來的適用於行動裝置的設計方案中解決。
