### ISSUE TITLE
add test-framework

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/demo-pttbbs#2]
We are not familiar with frontend development.

It will be great if someone can help us add test-framework.

https://reactjs.org/docs/testing.html

**Comment by solring** [comment]
Some small questions~

1. Should we open a dedicated branch for test?
2. Should we test by page or by components? or both? which first?

**Comment by chhsiao1981** [comment]
hi @solring ～

I know nothing about frontend-tests.

for this specific issue, I think some people can provide the test-template,
which can be a separate branch when developing that test-template.

once that test-template is finished, then we will setup github-action for PR
and add tests as many as possible. All the PRs need to pass the tests to be merged.

It may be easier to have 1 component as the 1st test.

**Comment by chhsiao1981** [comment]
https://reactjs.org/docs/testing-recipes.html
https://reactjs.org/docs/testing.html

Looks like that jest is a good choice for testing.

**Comment by solring** [comment]
@chhsiao1981:

Thanks! 
I'll take a look and try to start with one component or page.
I think maybe home page and register page can be nice choices since they both contain forms.
Is this fine for you?

**Comment by chhsiao1981** [comment]
hi @solring ～

both home-page and register-page are good start～

**Comment by jihchi** [comment]
I've created a PR relevant to this issue: #70

**Comment by chhsiao1981** [comment]
#70 resolves this issue.
#71  added to github-action.
