### ISSUE TITLE
cursor should be default in Cells

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/demo-pttbbs#37]
Sometimes the cursor becomes cursor:text in Cells.

Cursor should be default in Cells.
(and have `<a href></a>` as cursor:pointer in Cells (`<div.public_fixedDataTableCell_cellContent></div>`))

**Comment by solring** [comment]
Does this imply that a whole row should be a single link to the article?
Or only the title should be the link?

**Comment by chhsiao1981** [comment]
The whole row should be clickable to the article.

It's not necessary to be a single link though.
We can make it as clickable for every cell in the row if it is easier to implement.

**Comment by chhsiao1981** [comment]
#34 solves the issue.
