### ISSUE TITLE
增加轉錄/編輯/刪除 的 comments.

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/demo-pttbbs#90]
https://github.com/Ptt-official-app/go-openbbsmiddleware/blob/main/types/comment_type.go

middleware 層增加了轉錄 / 編輯 / 刪除的類別.
需要 parse 相對應的呈現方式.

https://github.com/Ptt-official-app/demo-pttbbs/blob/main/src/reducers/articlePage.js#L243

**Comment by solring** [comment]
examples:
<img width="1251" alt="Screenshot 2021-05-21 at 15 07 21" src="https://user-images.githubusercontent.com/4489005/119151078-9e0afd80-ba81-11eb-9ff0-483157886374.png">
<img width="1234" alt="Screenshot 2021-05-21 at 15 10 46" src="https://user-images.githubusercontent.com/4489005/119151083-9f3c2a80-ba81-11eb-80f3-4f5a5e75a0fc.png">

**Comment by solring** [comment]
想問一下這邊指的 轉錄 是轉一整篇文章(含它的comments)這樣嗎？
<img width="1075" alt="Screenshot 2021-05-21 at 15 23 49" src="https://user-images.githubusercontent.com/4489005/119152933-571e0780-ba83-11eb-997f-8d1f9011727f.png">

**Comment by chhsiao1981** [comment]
是的～

這個 issue 主要是指在 comments 裡需要 parse 這類訊息～

轉錄的動作目前還需要 backend 配合～

**Comment by chhsiao1981** [comment]
![image](https://user-images.githubusercontent.com/2970164/119154893-9c5d1d80-ba20-11eb-9451-002e6d6c8ec3.png)
