### ISSUE TITLE
增加向左鍵 => 離開的 hotkey

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/demo-pttbbs#91]
向左鍵 => 離開是很實用的 hotkey.

希望可以幫忙增加如此 feature.

**Comment by solring** [comment]
想確認一下：
1. 可以用上一頁的方式實作嗎？
2. 是所有頁面都要加這個功能嗎？還是主要加在看板列表/文章列表/文章本體？

thx!

**Comment by chhsiao1981** [comment]
(上一頁的方式不是很好～
 因為有些人會是直接拿到 link 點進來～)

 先實作文章本體 => 回到同一板的文章列表這個部分就好了～

 文章列表 => 看板列表的部分比較複雜～ 先不在這次範圍裡～)

**Comment by chhsiao1981** [comment]
#98 resolves this issue.
